#pragma once

#define FLICTRL_VERSION "0.1"

#define FLICTRL_OK  (0)
#define FLICTRL_ERR (1)
#define FLICTRL_ERR_NO_CAMERA_FOUND (2)
#define FLICTRL_ERR_CANNOT_OPEN_CAMERA_DEVICE (3)
#define FLICTRL_ERR_FAILED_ALLOC_FRAME (4)
#define FLICTRL_ERR_FAILED_GRAB_IMAGE (5)
